# This file was generated by GoReleaser. DO NOT EDIT.
cask "envrune" do
  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "d605df1e6a5eabb972a4d0e976ed93b5119d76b018b8594de9fa81481820a736"
      url "https://github.com/YagoLagrottiBracco/envrune/releases/download/v#{version}/envrune_#{version}_macos_arm64.tar.gz"
    end
    on_intel do
      sha256 "6d0c718f6ee2f389755f4e9127da7fbed512fc9283addf641d22a305ded3b222"
      url "https://github.com/YagoLagrottiBracco/envrune/releases/download/v#{version}/envrune_#{version}_macos_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "200c61813a3ac05ddf5455cbcfd15e158cf095034c23f3f4eca236c8194205e8"
      url "https://github.com/YagoLagrottiBracco/envrune/releases/download/v#{version}/envrune_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b1378619b2e641c0a9e134bbbfd1409a475d640af11add3928c3a5f70a17bfdc"
      url "https://github.com/YagoLagrottiBracco/envrune/releases/download/v#{version}/envrune_#{version}_linux_amd64.tar.gz"
    end
  end

  name "envrune"
  desc "A deliberate command-line workspace for encrypted environment variables."
  homepage "https://github.com/YagoLagrottiBracco/envrune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envrune"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envrune"]
    end
  end

  # No zap stanza required
end
