# This file was generated by GoReleaser. DO NOT EDIT.
cask "envrune" do
  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "a42571380c25c6a532445cfadd90a35951d146d500831993fce013157ef3400a"
      url "https://github.com/YagoLagrottiBracco/envrune/releases/download/v#{version}/envrune_#{version}_macos_arm64.tar.gz"
    end
    on_intel do
      sha256 "50d1c8365f4d84ab185fecda98d3ffcc976dcb7524dd4bc8a026f0cb5cd51025"
      url "https://github.com/YagoLagrottiBracco/envrune/releases/download/v#{version}/envrune_#{version}_macos_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4dc032009d4537cd26b010efd942c4ba80739aef44a57d66f3a6b5ea7434cf83"
      url "https://github.com/YagoLagrottiBracco/envrune/releases/download/v#{version}/envrune_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bdef5b61b65b41b4fc30bf5af66ee9a2a243fc0fbb01aa330d39ba7ab17d4d8f"
      url "https://github.com/YagoLagrottiBracco/envrune/releases/download/v#{version}/envrune_#{version}_linux_amd64.tar.gz"
    end
  end

  name "envrune"
  desc "A deliberate command-line workspace for encrypted environment variables."
  homepage "https://github.com/YagoLagrottiBracco/envrune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envrune"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envrune"]
    end
  end

  # No zap stanza required
end
