# This file was generated by GoReleaser. DO NOT EDIT.
cask "envrune" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "6d01d8c9b873a3df7b22d3582151433ddf949300a6bfb59057c52fd90f7401d6"
      url "https://github.com/YagoLagrottiBracco/envrune/releases/download/v#{version}/envrune_#{version}_macos_arm64.tar.gz"
    end
    on_intel do
      sha256 "82cdf0e62e49558d435ea7dcea4b1e7cf2f38c96eb15e55a4fbfbb01fca1d7ab"
      url "https://github.com/YagoLagrottiBracco/envrune/releases/download/v#{version}/envrune_#{version}_macos_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d621f09f658907e9f887dd51e9c88b601d5a4839c62ea853209ec7e130b44639"
      url "https://github.com/YagoLagrottiBracco/envrune/releases/download/v#{version}/envrune_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e7a54f67533124c3bd2d264dde7c09e78126c14696a598c2c29b8cf29d950d19"
      url "https://github.com/YagoLagrottiBracco/envrune/releases/download/v#{version}/envrune_#{version}_linux_amd64.tar.gz"
    end
  end

  name "envrune"
  desc "A deliberate command-line workspace for encrypted environment variables."
  homepage "https://github.com/YagoLagrottiBracco/envrune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envrune"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envrune"]
    end
  end

  # No zap stanza required
end
